### ISSUE TITLE
Leftover issues from v1.2

### ISSUE THREAD

**Issue by dorcastan** [AY1920S1-CS2103T-T13-4/main#106]
- [ ] Miscellaneous folder-related fixes (@openorclose)
  - [x] Move folders to dashboard 
  - [ ] Don't display $$$ROOT in BookmarkCard (#81)
  - [ ] Throw error to solve #85  
- [x] Set bookmark folders to ROOT before importing (@dorcastan)
- [ ] Link address bar to online panel (@kxyoke) (will be settled in #110)

- [x] Merge reminder association (@TSAI-HSIAO-HAN)
