### ISSUE TITLE
Implement complete undo and redo

### ISSUE THREAD

**Issue by Na-Nazhou** [AY1920S1-CS2103T-T13-4/main#59]
- [ ] Final check on the undo and redo
- [ ] Amend the implementation to support more undoable commands if possible (annotate, etc)

Nice to have: 
- [x] Support undo/redo multiple commands (`undo 3`)
- [x] Currently, command history is not stored (only a list of states are stored in VersionedMark class). If possible, we can also store command history and display to users what command they are undoing/redoing.
- Support undo and redo even the application is closed (to implement this, history states of Mark must be stored somewhere and there must be a list of history states to be stored. (not going to do this because of memory)
